apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-wn2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmqcluster-0
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: rabbitmqcluster
    app.kubernetes.io/part-of: rabbitmq
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  hostPath:
    path: /mnt/data/rabbitmq

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmqcluster-1
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: rabbitmqcluster
    app.kubernetes.io/part-of: rabbitmq
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  hostPath:
    path: /mnt/data/rabbitmq

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmqcluster-2
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: rabbitmqcluster
    app.kubernetes.io/part-of: rabbitmq
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  hostPath:
    path: /mnt/data/rabbitmq
