apiVersion: v1
kind: Service
metadata:
  name: rabbitmqcluster
  namespace: rabbitmq-system
spec:
    type: NodePort
    ports:
      - name: amqp
        port: 5672
        nodePort: 31672  # 원하는 NodePort 지정 (30000-32767 사이)
      - name: management
        port: 15672
        nodePort: 31672  # 관리 UI용 NodePort (원하는 포트로 변경 가능)
