apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: middleware
  labels:
    app: mysql
    tier: middleware
spec:
  ports:
  - port: 3306
    name: mysql
    nodePort: 30306
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: mysql
    tier: middleware

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmqcluster
  namespace: rabbitmq-system
spec:
  ports:
  - name: amqp
    port: 5672
    nodePort: 31672     
  - name: management
    port: 15672
    nodePort: 31672 
  type: NodePort
